name: Conditional Workflow
on:
  push:
    paths:
      - "backend/**"

jobs:
  conditional-workflows:
    runs-on: windows-latest
    steps:
      - name: Build backend image
        run: echo "Backend image is building"
