name:  Value Pass Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "unnamed"

jobs:
  get-value-workflow:
    runs-on: windows-latest
    outputs:
      msg: ${{ steps.generate-message.outputs.message }}
    steps:
      - name: Generate message
        id: generate-message
        run: |
          echo "message=Hello, ${{ github.event.inputs.name }}!" >> $GITHUB_OUTPUT

  print-value-workflow:
    runs-on: windows-latest
    needs: [get-value-workflow]
    steps:
      - name: print message
        run: |
          echo "${{ needs.get-value-workflow.outputs.msg }}"

